#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     frontRightMotor, tmotorTetrix, openLoop, reversed, driveRight)
#pragma config(Motor,  mtr_S1_C1_2,     frontLeftMotor, tmotorTetrix, openLoop, driveLeft)
#pragma config(Motor,  mtr_S1_C2_1,     backRightMotor, tmotorTetrix, openLoop, reversed, driveRight)
#pragma config(Motor,  mtr_S1_C2_2,     backLeftMotor, tmotorTetrix, openLoop, driveLeft)
#pragma config(Motor,  mtr_S1_C3_1,     centerMotor,   tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     scissorMotor,  tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     pickupMotor,   tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     motorK,        tmotorTetrix, openLoop)
//*!!Code automatically generated by the amazing Gautam               !!*//


#include "JoystickDriver.c"
void initializeRobot() {
	return;
}
void autonomous ()
{

		motor[frontLeftMotor] = 100;
		motor[frontRightMotor] = 100;
		motor[backLeftMotor] = 100;
		motor[backRightMotor] = 100
		;
		wait1Msec(3000);
		motor[frontLeftMotor] = 0;
		motor[frontRightMotor] = 0;
		motor[backLeftMotor] = 0;
		motor[backRightMotor] = 0;
}
task main()
{
	initializeRobot();
	waitForStart();
	autonomous();
}
