#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     frontRightMotor, tmotorTetrix, openLoop, reversed, driveRight)
#pragma config(Motor,  mtr_S1_C1_2,     frontLeftMotor, tmotorTetrix, openLoop, driveLeft)
#pragma config(Motor,  mtr_S1_C2_1,     backRightMotor, tmotorTetrix, openLoop, reversed, driveRight)
#pragma config(Motor,  mtr_S1_C2_2,     backLeftMotor, tmotorTetrix, openLoop, driveLeft)
#pragma config(Motor,  mtr_S1_C3_1,     centerMotor,   tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     scissorMotor,  tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     pickupMotor,   tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     motorK,        tmotorTetrix, openLoop)
#pragma config(Sensor, S3,     lightSensor,         sensorLightActive)
//*!!Code automatically generated by the amazing Gautam               !!*//

#include "JoystickDriver.c"

void ir();

void initializeRobot()
{
	return;
}

void autonomous ()
{
	  for(int i = 0; i < 1; i ++) {
	  	ir();
	  }
		motor[frontLeftMotor] = 100;
		motor[frontRightMotor] = 100;
		motor[backLeftMotor] = 100;
		motor[backRightMotor] = 100
		;
		wait1Msec(3000);
		motor[frontLeftMotor] = 0;
		motor[frontRightMotor] = 0;
		motor[backLeftMotor] = 0;
		motor[backRightMotor] = 0;
}

int ir()
{
   wait1Msec(50);                        // The program waits 50 milliseconds to initialize the light sensor.
   return SensorValue(lightSensor);
   /*
   while(true)                           // Infinite loop
   {
      if(SensorValue(lightSensor) < 45)  // If the Light Sensor reads a value less than 45:
      {
        motor[motorB] = 60;                  // Motor B is run at a 60 power level.
        motor[motorC] = 20;                  // Motor C is run at a 20 power level.
      }
      else                               // If the Light Sensor reads a value greater than or equal to 45:
      {
        motor[motorB] = 20;                  // Motor B is run at a 20 power level.
        motor[motorC] = 60;                  // Motor C is run at a 60 power level.
      }
   }
   */
}

task main()
{
	initializeRobot();
	waitForStart();
	autonomous();
}
