#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     HTIRS,          sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  mtr_S1_C1_1,     frontRightMotor, tmotorTetrix, openLoop, reversed, driveRight)
#pragma config(Motor,  mtr_S1_C1_2,     frontLeftMotor, tmotorTetrix, openLoop, driveLeft)
#pragma config(Motor,  mtr_S1_C2_1,     backRightMotor, tmotorTetrix, openLoop, reversed, driveRight)
#pragma config(Motor,  mtr_S1_C2_2,     backLeftMotor, tmotorTetrix, openLoop, driveLeft)
#pragma config(Motor,  mtr_S1_C3_1,     centerMotor,   tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     drawerMotor,   tmotorTetrix, openLoop, encoder)
#pragma config(Servo,  srvo_S1_C4_1,    draggerServo,         tServoStandard)
#pragma config(Servo,  srvo_S1_C4_2,    clickerServo,         tServoNone)
#pragma config(Servo,  srvo_S1_C4_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
//Hey you're looking at Gautam's code! Make sure to upload to git regularly or I shall become murderously cantankerous//
//BTW MAEK SURE U TSET TEH COAD BFORE U PUT IT ON TEH GIT!
/* TO DO List: Please TEST and check off items
	1. v Make basic drive and deadzone functions actually work
	2. v Functionify
	3. Encoder support
	4. v Scissor lift & Pickup support
	5. Actual autonomous code
*/
//======================================= THIS IS A SEPARATOR =====================================================
/* If you have free time (which you shouldn't), you can:
	1. Make a LOLCODE to ROBOTC interpreter NO!
	2. Teach younger programmers to code
	3. Take over the world
	4. Fix grammer
*/

// Constants are defined here. Is anyone listening?
#define servoPosition1 25
#define servoPosition2 70
#define servoPosition3 150

// Constants are no longer defined here

// VERSION 1.0.6 Compiling code that can drive all basic parts with a joystick.

void basicDrive(TJoystick joystick)
{
	if (joystick.joy1_y1 <= -10 || joystick.joy1_y1 >= 10 || joystick.joy1_y2 <= -10 || joystick.joy1_y2 >= 10) {
			motor[frontLeftMotor] = joystick.joy1_y1;
			motor[frontRightMotor] = joystick.joy1_y2;
			motor[backLeftMotor] = joystick.joy1_y1;
			motor[backRightMotor] = joystick.joy1_y2;
		} //end if

		else {

			motor[frontLeftMotor] = 0;
			motor[frontRightMotor] = 0;
			motor[backLeftMotor] = 0;
			motor[backRightMotor] = 0;

		} //end else

		if (joystick.joy1_TopHat == 1 || joystick.joy1_TopHat == 2 || joystick.joy1_TopHat == 3) {

			motor[centerMotor] = 50;

		} //end if
		else if (joystick.joy1_TopHat == 5 || joystick.joy1_TopHat == 6 || joystick.joy1_TopHat == 7) {
			motor[centerMotor] = -50;
		} //end else if
		else {
			motor[centerMotor] = 0;
		} //end else
} //end function: basicDrive

void peripherals (TJoystick joystick)
{
	if (joystick.joy2_y1 <= -10 || joystick.joy2_y1 >= 10) {
		motor[drawerMotor] = joystick.joy2_y1;
	} else {
		motor[drawerMotor] = 0;
	} //end if

	if (joy2Btn(1) == 1) {
		servo[clickerServo] = servoPosition1;
	} else if (joy2Btn(2) == 1) {
		servo[clickerServo] = servoPosition2;
	} else if (joy2Btn(3) == 1) {
		servo[clickerServo] = servoPosition3;
	}

	if (joystick.joy2_y1 >= 10) {
		servo[draggerServo] = servo[draggerServo] + 1;
	} else if (joystick.joy2_y1 <= -10) {
		servo[draggerServo] = servo[draggerServo] - 1;
	}

} //end function: peripherals

task main() {

	while (1) {
		getJoystickSettings(joystick);
		basicDrive(joystick);
		peripherals(joystick);
	} //end while
} //end task
