#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     frontLeftMotor, tmotorTetrix, openLoop, driveLeft)
#pragma config(Motor,  mtr_S1_C1_2,     backLeftMotor, tmotorTetrix, openLoop, driveLeft)
#pragma config(Motor,  mtr_S1_C2_1,     frontRightMotor, tmotorTetrix, openLoop, driveRight)
#pragma config(Motor,  mtr_S1_C2_2,     backRightMotor, tmotorTetrix, openLoop, driveRight)
#pragma config(Motor,  mtr_S1_C3_1,     centerMotor,   tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     motorI,        tmotorTetrix, openLoop)
//*!!Code automatically generated by the amazing Gautam               !!*//

#include "JoystickDriver.c"
//Hey you're looking at Gautam's code! Make sure to upload to git regularaly or I shall become murderously cantankerous//
//BTW MAEK SURE U TSET TEH COAD BFORE U PUT IT ON TEH GIT!
/* TO DO List: Please TEST and check off items
	1. Make basic drive and deadzone functions actually work
	2. Functionify
	3. Encoder support
	4. Scissor lift & Pickup support
	5. Actual autonomous code
*/
//======================================= THIS IS A SEPARATOR =====================================================
/* If you have free time (which you shouldn't), you can:
	1. Make a LOLCODE to ROBOTC interpreter
	2. Teach younger programmers to code
	3. Take over the world
	4. Fix grammar
*/

task main()
{
	while (1) {
		getJoystickSettings(joystick);
		//if (joystick.joy1_y1 <= -10 || joystick.joy1_y1 >= 10) {
			motor[frontLeftMotor] = joystick.joy1_y1;
			motor[frontRightMotor] = joystick.joy1_y1;
			motor[backLeftMotor] = joystick.joy1_y1;
			motor[backRightMotor] = joystick.joy1_y1;
		//}
		//commented out 10-22 because of not working
		/*else {

			motor[frontLeftMotor] = 0;
			motor[frontRightMotor] = 0;
			motor[backLeftMotor] = 0;
			motor[backRightMotor] = 0;

		}*/

		/*if (joystick.joy1_x1 <= -10 || joystick.joy1_x1 >= 10) {

			motor[centerMotor] = joystick.joy1_x1;

		}
		else {
			motor[centerMotor] = 0;
		}*/
		/*
			motor[frontLeftMotor] = 50;
			motor[frontRightMotor] = 50;
			motor[backLeftMotor] = 50;
			motor[backRightMotor] = 50;
		*/
	} //end while
} //end task
