#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     FLMotor,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     FRMotor,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     BLMotor,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     BRMotor,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     motorH,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     motorI,        tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(true) {
		motor[FLMotor] = 50;
		motor[FRMotor] = 50;
		motor[BLMotor] = 50;
		motor[BRMotor] = 50;
		motor[motorH] = 50;
	}
}
